name = "vite-react-worker"
compatibility_date = "2024-09-07"

[build]
command = "npm run build"
publish = "dist"
pages_build_output_dir = "./dist"

[functions]
directory = "functions"

[[d1_databases]]
binding = "DB"
database_name = "ittyvite"
database_id = "d94879ca-7319-421f-82c4-1e13cad5e649"
